### ISSUE TITLE
训练自己的数据集报错：t, c, o = _fitpack._parcur(ravel(transpose(x)), w, u, ub, ue, k, ValueError: Invalid inputs.

### ISSUE THREAD

**Issue by dhddxdhd** [ychensu/LRANet#2]
定位是tck, u = splprep([x, y], k=3 if polygon.shape[0] >=5 else 2, s=0)这个函数报错，请问是为什么呢

**Comment by ychensu** [comment]
这可能是因为标注的问题，经过数据增强后，存在一些重复的点，将其过滤后再试试
