### ISSUE TITLE
训练时mmocr框架注册表相关报错

### ISSUE THREAD

**Issue by fuxiangzhai** [ychensu/LRANet#3]
[错误信息.txt](https://github.com/user-attachments/files/15904317/default.txt)
作者您好，感谢您出色的工作，我在使用3张3090训练时出现了mmocr框架注册表相关的报错，报错如文件所示，不过奇怪的是，这个错误时有时无，自己不知缘故，请麻烦看一下，求解答，感谢。

**Comment by ychensu** [comment]
删掉build后再重新python setup.py build develop试试
