### ISSUE TITLE
Request: Could you share the eigenanchors generation code?

### ISSUE THREAD

**Issue by ChangKe1024** [ychensu/LRANet#7]
Thank you for sharing this amazing project! I am particularly interested in understanding the process of eigenanchors generation as it plays a crucial role in the method.
I was wondering if you could share the code or provide some additional details about how the eigenanchors are generated. Thank you for your time and for creating such a valuable resource!

**Comment by ychensu** [comment]
Thank you for your interest, we will publish the generation details and an improved version of lranet in the future. You can first construct the contour matrix as described in Section 3.1, and then extract the left singular vectors as eigenanchor after the SVD.

**Comment by ChangKe1024** [comment]
Thank you for the helpful information! I will try following the details provided.Looking forward to the release of the improved version of LRANet.
